package com.amazonaws.mobile.content;
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//


import com.amazonaws.services.s3.model.ObjectMetadata;

import java.util.Map;

public class S3ContentMeta implements ContentItem {
    private final ObjectMetadata objectMetadata;
    final String objectKey;
    private ContentState contentState;

    public S3ContentMeta(final String objectKey,
                         final ObjectMetadata objectMetadata,
                         final ContentState contentState) {
        this.objectKey = objectKey;
        this.objectMetadata = objectMetadata;
        this.contentState = contentState;
    }

    /** {@inheritDoc} */
    @Override
    public long getLastModifiedTime() {
        return objectMetadata.getLastModified().getTime();
    }

    /** {@inheritDoc} */
    @Override
    public String getFilePath() {
        return objectKey;
    }

    /** {@inheritDoc} */
    @Override
    public long getSize() {
        return objectMetadata.getContentLength();
    }

    /** {@inheritDoc} */
    @Override
    public ContentState getContentState() {
        return contentState;
    }

    /** {@inheritDoc} */
    @Override
    public void setContentState(final ContentState contentState) {
        this.contentState = contentState;
    }

    @Override
    public Map<String, String> getUserMetaData() {
        return objectMetadata.getUserMetadata();
    }

    @Override
    public void setUserMetaData(Map<String, String> metaData) {

    }


    /**
     * @return the S3 object summary representing this content.
     */
    public ObjectMetadata getObjectMetadata() {
        return objectMetadata;
    }
}
